config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end
  # 顧客用
# URL /customers/sign_in ...
devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

 # URLは変えない/ファイル構成だけ指定のパス
  scope module: :public do
    root to: 'homes#top'
    resources :users, only: [:show, :edit, :update] do
      patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
      resource :relationships, only: [:create, :destroy]
    end
    resources :lists, only: [:create, :index, :show, :edit, :update, :destroy]
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      get 'edit_detail/:route_id' => 'posts#edit_detail', as: 'edit_detail'
      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    delete '/posts/:id/destroy_post' =>'posts#destroy_post', as: 'destroy_post'
  end

  #URLは指定のパス/ファイル構成も指定のパス
  namespace :admin do
    root to: 'homes#top'
    resources :users, only: [:index, :show, :edit, :update]
  end

end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <% style = key %>
  <% style = 'success' if style == 'notice' %>
  <% style = 'danger' if style == 'alert' %>
  <p class="alert alert-<%= style %>">
    <%= value %>
  </p>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="bg-5">
        <!--リストをサイドに固定-->
        <div class="sidebox" data-spy="affix" data-offset-top="100">
        <!--ロゴ-->
          <div class="mt-2 mb-4">
            <a href="/">
              <%= image_tag "tabitomologo.png", size: "160x160" %>
            </a>
          </div>
          <!--ナビゲーションバー-->
          <div class="text-info">
            <ul class="nav flex-column list-unstyled">
              <% if admin_signed_in? %>
              <!--Adminログイン時-->
                <div class="mb-2">
                  <li class="nav-item">
                    <%= link_to admin_users_path, class: 'btn btn-outline-info btn-block btn-lg' do %>
                      <i class="fas fa-user fa-fw"></i>
                      Users
                    <% end %>
                  </li>
                </div>
                <li class="nav-item">
                  <%= link_to destroy_admin_session_path, method: :delete, class: 'btn btn-outline-info btn-block btn-lg' do %>
                    <i class="fa-solid fa-right-from-bracket fa-fw"></i>
                    Log out
                  <% end %>
                </li>
              <% elsif user_signed_in? %>
                <!--Userログイン時-->
                <!--ダッシュボード-->
                <div class="mb-2">
                  <li class="nav-item">
                    <%= link_to root_path, class: 'btn btn-outline-info btn-block btn-lg' do %>
                      <i class="fas fa-home fa-fw"></i>
                      Dashboard
                    <% end %>
                  </li>
                </div>
                <!--マイページ-->
                <% if current_user.email != 'guest@example.com' %>
                  <div class="mb-2">
                    <li class="nav-item">
                      <%= link_to user_path(current_user.id), class: 'btn btn-outline-info btn-block btn-lg' do %>
                        <i class="fas fa-user fa-fw"></i>
                        Mypage
                      <% end %>
                    </li>
                  </div>
                <% end %>
                <!--パッキング-->
                <div class="mb-2">
                <li class="nav-item">
                  <%= link_to lists_path, class: 'btn btn-outline-info btn-block btn-lg' do %>
                    <i class="fas fa-suitcase-rolling fa-fw"></i>
                    Packing
                  <% end %>
                </li>
                </div>
                <!--プランニング-->
                <div class="mb-2">
                <li class="nav-item">
                  <%= link_to new_post_path, class: 'btn btn-outline-info btn-block btn-lg' do %>
                    <i class="fas fa-plane fa-fw"></i>
                    Planning
                  <% end %>
                </li>
                </div>
                <!--ログアウト-->
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-outline-info btn-block btn-lg' do %>
                    <i class="fa-solid fa-right-from-bracket fa-fw"></i>
                    Log out
                  <% end %>
                </li>
              <% else %>
                <!--User未ログイン時-->
                <!--ダッシュボード-->
                <div class="mb-2">
                  <li class="nav-item">
                    <%= link_to root_path, class: 'btn btn-outline-info btn-block btn-lg' do %>
                      <i class="fas fa-home fa-fw"></i>
                      Dashboard
                    <% end %>
                  </li>
                </div>
                 <!--ゲストログイン-->
                <div class="mb-2">
                  <li class="nav-item">
                    <%#= link_to root_path, class: 'btn btn-outline-info btn-block btn-lg' do %>
                    <%= link_to public_guest_sign_in_path, method: :post, class: 'login btn btn-outline-info btn-block btn-lg' do %>
                      <i class="fas fa-laugh fa-fw"></i>
                      Guest
                    <% end %>
                  </li>
                </div>
                <!--ログイン-->
                <div class="mb-2">
                  <li class="nav-item">
                    <%= link_to new_user_session_path, class: 'btn btn-outline-info btn-block btn-lg' do %>
                      <i class="fa-solid fa-right-to-bracket fa-fw"></i>
                      Login
                    <% end %>
                  </li>
                </div>
                <!--新規登録-->
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: 'btn btn-outline-info btn-block btn-lg' do %>
                    <i class="fa-solid fa-user-plus fa-fw"></i>
                    Sign up
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
      <div class="triangle"></div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Tabitomo</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!--FontAwesome導入-->
    <script src="https://kit.fontawesome.com/eabeaac4fc.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= include_gon %>
    <!--app/javascript 配下のファイルを参照-->
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <!--application.cssの適用-->
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <main>
      <div class="container">
        <div class="row">
          <!--ヘッダーがサイドのため部分テンプレで定義-->
          <div class="col-md-2">
            <%= render 'layouts/header' %>
          </div>
          <!--main部分-->
          <div class="col-md-10">
            <%= render 'layouts/flash' %>
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
    <footer>
      <div class="mb-5"></div>
    </footer>
    <!--Bootstrapのscript-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>